feature: support string value
yanivam/react-svg-worldmap pull request #127
Opened 2022-06-15 16:13 UTC by kennethbigler

I could not get the build to work locally. I was getting some strange errors:

```js
...

../node_modules/@types/react/index.d.ts:3115:19 - error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}, any>' and 'Component<any, {}, any>'.
  Named property 'refs' of types 'Component<any, {}, any>' and 'Component<any, {}, any>' are not identical.

3115         interface ElementClass extends React.Component<any> {
                       ~~~~~~~~~~~~

../node_modules/@types/react/index.d.ts:3123:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

3123         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  ../node_modules/@types/react-router/node_modules/@types/react/index.d.ts:3088:14
    3088         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.

Found 180 errors in 2 files.

Errors  Files
   176  ../node_modules/@types/react-router/node_modules/@types/react/index.d.ts:3088
     4  ../node_modules/@types/react/index.d.ts:3115
```

I also didn't see any tests, but this is roughly what I had in mind to support `value` as a string or a `0` value.

2022-06-15 16:15 UTC, Josh-Cena commented
For tests, just add an example under `website/src/components` and its corresponding page under `website/src/pages/examples`.

I'll help you fix the TS errors.

2022-06-15 16:18 UTC, kennethbigler commented
> For tests, just add an example under `website/src/components` and its corresponding page under `website/src/pages/examples`.
> 
> I'll help you fix the TS errors.
> 
> This is to fix #126, correct?

That is correct! And ya do let me know what to do to fix those errors, I can definitely make an example :)

2022-06-15 16:19 UTC, Josh-Cena commented
The error is unrelated. I would fix that first and get back to you. Thanks!

2022-06-15 16:43 UTC, Josh-Cena requested changes
I've made some refactors to make the code lint & compile.

Please:

1. Explain what a string `value` represents, because it's not immediately obvious from your issue description.

If the explanation makes sense and we agree to accept this API extension, please:

2. Add docs.
3. Add an example. Especially highlighting how a value of `0` differs from a value of `undefined`.

2022-06-16 15:38 UTC, kennethbigler commented
@Josh-Cena I have updated the description, let me know if that makes sense! I am happy to elaborate if needed.

With your approval I will continue on with steps 2 and 3 :)

2022-06-16 15:42 UTC, Josh-Cena commented
I see. Couldn't you simply change the tooltip text in that case, though?

https://yanivam.github.io/react-svg-worldmap/examples/localization

2022-06-16 16:24 UTC, Josh-Cena commented
Yes, I agree that `value` should be easier to use than `tooptipTextFunction`. Feel free to add docs and an example! (And do mention that using a string `value` is just a simpler way of using `tooptipTextFunction`)

2022-06-17 16:19 UTC, Josh-Cena commented
I'm thinking about several things:

1. We should make `WorldMap` a generic function, so that we can avoid typing the callback as always passing `value: number | string` when in practice most users would not have string values.
2. When we have a mix of both, the strings should be treated as having value `0`.
3. We should have some kind of normalization algorithm for the colors. I still think having `0` mean "no color" is a valuable thing to do, although it falls apart if you have negative values. Maybe we need a logarithmic color scale.

2022-06-17 16:25 UTC, kennethbigler commented
> I'm thinking about several things:
> 
> 1. We should make `WorldMap` a generic function, so that we can avoid typing the callback as always passing `value: number | string` when in practice most users would not have string values.
> 2. When we have a mix of both, the strings should be treated as having value `0`.
> 3. We should have some kind of normalization algorithm for the colors. I still think having `0` mean "no color" is a valuable thing to do, although it falls apart if you have negative values. Maybe we need a logarithmic color scale.

1. I am not sure where you mean for this, can you elaborate?
2. I am definitely happy to make `string` be treated as a `0` value.
3. especially as you say to support negative values, I really don't think it is that hard for users to set value to `undefined` to get no color.

2022-06-17 16:29 UTC, Josh-Cena commented
The error is really messed up. @yanivam did not push the 2.0.0-alpha.1 publish commit to master, so the website is not picking up the local version. I would manually push a commit.

2022-06-17 16:33 UTC, kennethbigler commented
@Josh-Cena it looks like the error is from the fact that website is looking for an npm build. I am going to try updating to local linking instead.

As for the point #2, should I make string be 0, or `minValue`? As you said, if we support negative values that could be tricky. I am thinking `minValue` would be better.

2022-06-17 16:35 UTC, Josh-Cena commented
> it looks like the error is from the fact that website is looking for an npm build

The problem is because the website is depending on a newer version of react-svg-worldmap than what the workspace has (because @yanivam didn't push the commit where he published 2.0.0-alpha.1). I've fixed it in https://github.com/yanivam/react-svg-worldmap/commit/6493953d32407d2f5e0f0022d6a39d75b5b2cc32. Now it surfaces another bug in my lint workflow.

2022-06-17 16:38 UTC, Josh-Cena commented
> should I make string be 0, or `minValue`? As you said, if we support negative values that could be tricky. I am thinking `minValue` would be better.

Yeah, I'm not sure. I would really have to think about the semantics. For one thing: `minValue` would still have a color. `0` was originally designed to have absolutely no color. That's why I said we probably need a normalization algorithm.

2022-06-17 16:50 UTC, Josh-Cena commented
OK, making it a generic function works pretty nicely. If you directly pass a literal array, you get the additional benefit of inferring literal types instead of plain `string | number`.

2022-06-17 16:54 UTC, Josh-Cena commented
@kennethbigler No need to link locally... I've already fixed this. I'll revert your last commit because it overwrote mine.

2022-06-17 17:06 UTC, kennethbigler commented
> @kennethbigler It's looking good from me. I don't have any more reviews. I'll think about the semantics of having "0" mean "no color" in the coming days, and probably merge this next week. Feel free to share your thoughts as well.

@Josh-Cena I gave my opinion above, I think it would be best that if you want no color, you should change the value to `undefined`.

2022-06-17 18:46 UTC, yanivam commented
Whoa, saw this thread and catching up now. @Josh-Cena and @kennethbigler do you all need me to do something? I can publish a new version if need be. Let me know what needs to be done on my end. This update looks good to me.

2022-06-17 20:13 UTC, kennethbigler commented
Thanks @yanivam! I don't think so. 
Just excited for this to be available and waiting on @Josh-Cena to decide the exact alg he is hoping for.
Big shout out to @Josh-Cena for all the awesome help 🎉

2022-06-24 19:14 UTC, kennethbigler commented
@Josh-Cena any update?

2022-07-07 14:45 UTC, Josh-Cena commented on docs/customization.md
> +    countryValue !== undefined
```suggestion
    calculatedValue !== undefined
```

2022-07-07 14:45 UTC, Josh-Cena commented on docs/customization.md
> +      ? 0.1 + (1.5 * (countryValue - minValue)) / (maxValue - minValue)
```suggestion
      ? 0.1 + (1.5 * (calculatedValue - minValue)) / (maxValue - minValue)
```

2022-07-07 14:50 UTC, merged